// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadDotenv } from "dotenv";
import { defineConfig } from "prisma/config";

// Prisma CLI does not read Next.js .env.local automatically.
// Load local overrides first, then fallback to standard .env.
loadDotenv({ path: ".env.local" });
loadDotenv();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] ?? "",
  },
});
